### ISSUE TITLE
Pills in a tab reset when a selection is made

### ISSUE THREAD

**Issue by sfc-gh-agaiduk** [jrieke/streamlit-pills#10]
I observed a very peculiar bug that is happening when combining pills with tabs. When a pill is selected, it immediately resets, even though the selector value is assigned correctly. Here is a minimal reproducible example with the screen recording:
```
import streamlit as st
from streamlit_pills import pills

st.title("Pills tabs app")

if "setup_complete" not in st.session_state:
    st.write("Hello world!")
    st.session_state["setup_complete"] = True

c1, c2 = st.tabs(["Tab 1", "Tab 2"])
with c1:
    pill_selector = pills(
        "Pill selector", ["Option 1", "Option 2", "Option 3"], ["🍀", "🎈", "🌈"]
    )
    st.write("Pill selector option: ", pill_selector)
``` 
![pills](https://github.com/jrieke/streamlit-pills/assets/119378200/74542558-2d92-4980-8ae9-03c63668c9ac)

To observe this behavior, 2 conditions must be met:
* Pills are used within tabs - if pills are outside tabs, they render correctly;
* We do some pre-processing during a first-time setup - i.e., if `st.write("Hello world!")` is moved outside of `if "setup_complete" not in st.session_state` block (or commented out), the pills are rendered correctly.

In a similar setup, `st.radio` selector does not reset:
```
import streamlit as st

st.title("Pills tabs app")

if "setup_complete" not in st.session_state:
    st.write("Hello world!")
    st.session_state["setup_complete"] = True

c1, c2 = st.tabs(["Tab 1", "Tab 2"])
with c1:
    radio_selector = st.radio(
        "Radio selector", ["Option 1", "Option 2", "Option 3"], horizontal=True
    )
    st.write("Radio selector option: ", radio_selector)
```
![radio](https://github.com/jrieke/streamlit-pills/assets/119378200/7430f484-0020-48e3-87d2-cf39bf83503e)

As a workaround in my actual use case, I followed a suggestion in https://github.com/streamlit/streamlit/issues/6257 based on [this](https://discuss.streamlit.io/t/returning-to-the-right-tab-after-clicking-button/31554) Streamlit question - if the tabs are rendered before the `if "setup_complete" not in st.session_state` block, the pills selector works correctly:
```
import streamlit as st
from streamlit_pills import pills

st.title("Pills tabs app")

c1, c2 = st.tabs(["Tab 1", "Tab 2"])
with c1:
    pill_selector = pills(
        "Pill selector", ["Option 1", "Option 2", "Option 3"], ["🍀", "🎈", "🌈"]
    )
    st.write("Pill selector option: ", pill_selector)

if "setup_complete" not in st.session_state:
    st.write("Hello world!")
    st.session_state["setup_complete"] = True
```

**Comment by jrieke** [comment]
Streamlit has pills as a built-in feature now, using `st.pills`. See [docs](https://docs.streamlit.io/develop/api-reference/widgets/st.pills). Please use that instead of this component! I think that issue shouldn't exist in that feature but if it does, please file an issue on the streamlit repo.
