### ISSUE TITLE
Can you add on_change for pills 

### ISSUE THREAD

**Issue by ZJCODE** [jrieke/streamlit-pills#12]
In my user interface, I want to execute a callback, like on_change, when a user selects a pill

**Comment by lucasrodes** [comment]
i would be interested in this feature too

**Comment by jrieke** [comment]
Streamlit has pills as a built-in feature now, using `st.pills`. This command also comes with `on_change`. See [docs](https://docs.streamlit.io/develop/api-reference/widgets/st.pills). Please use that instead of this component!
