### ISSUE TITLE
Multi select 

### ISSUE THREAD

**Issue by cceyda** [jrieke/streamlit-pills#2]
It would be nice to have st.multiselect functionality 🥺 
Doesn't even have to be fancy with ctrl+ selection, just  toggle like select/unselect.

**Comment by cceyda** [comment]
okay couldn't resist so made PR https://github.com/jrieke/streamlit-pills/pull/3

**Comment by vrdn-23** [comment]
@jrieke I agree that this would be a nice addition to the feature! Any chance we can merge it?
Thanks a lot @cceyda !

**Comment by cceyda** [comment]
@vrdn-23 until it is merged you can use it by pip installing `git+https://github.com/cceyda/streamlit-pills@multiselect_release#egg=streamlit-pills`

**Comment by avrabyt** [comment]
+1 for the feature request suggested by @cceyda . Just now I felt it's need . 
Would be great to have it implemented in the main package :)

**Comment by CHerSun** [comment]
> @vrdn-23 until it is merged you can use it by pip installing `git+https://github.com/cceyda/streamlit-pills@multiselect_release#egg=streamlit-pills`

@cceyda thank you for sharing! Was looking for that

**Comment by sooftware** [comment]
@cceyda  Awesome! Thank you for sharing!

**Comment by austinmw** [comment]
Would be great to add this!

**Comment by Trezorro** [comment]
Please add this! 👍

**Comment by ThermalFlow** [comment]
Would be great to add this feature!

**Comment by jrieke** [comment]
Streamlit has pills as a built-in feature now, using st.pills. See [docs](https://docs.streamlit.io/develop/api-reference/widgets/st.pills). Please use that instead of this component! It also supports multiselect via `selection_mode="multi"`.
