### ISSUE TITLE
label string : supporting colored text option 

### ISSUE THREAD

**Issue by avrabyt** [jrieke/streamlit-pills#4]
Thanks for this component, it elevates the aesthetic aspect of the app , in addition to `st.radio`  widget.

**Feature request** : if it's possible to add markdown option to the label. Specially in my case I would like to add a color to the label string , like streamlit widgest - ` st.text_input ` where : colored text, using the syntax :color[text to be colored] is supported. 

Thanks
Avra

**Comment by jrieke** [comment]
Streamlit has pills as a built-in feature now, using st.pills. See [docs](https://docs.streamlit.io/develop/api-reference/widgets/st.pills). Please use that instead of this component! It also supports colored text and all other markdown features for the label.
