### ISSUE TITLE
Doesn't render on EC2

### ISSUE THREAD

**Issue by tushar-31093** [jrieke/streamlit-pills#5]
![image](https://user-images.githubusercontent.com/40886260/222391704-61726d70-e57c-489f-9867-707414cb7475.png)

**Comment by jrieke** [comment]
Streamlit has pills as a built-in feature now, using st.pills. See [docs](https://docs.streamlit.io/develop/api-reference/widgets/st.pills). Please use that instead of this component! I think that issue shouldn't exist in that feature.
